# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.api.support_api import SupportApi


class TestSupportApi(unittest.TestCase):
    """SupportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SupportApi()

    def tearDown(self) -> None:
        pass

    def test_support_departments_list(self) -> None:
        """Test case for support_departments_list

        """
        pass

    def test_support_departments_list2(self) -> None:
        """Test case for support_departments_list2

        """
        pass

    def test_support_tickets_close_create(self) -> None:
        """Test case for support_tickets_close_create

        """
        pass

    def test_support_tickets_close_create2(self) -> None:
        """Test case for support_tickets_close_create2

        """
        pass

    def test_support_tickets_create(self) -> None:
        """Test case for support_tickets_create

        """
        pass

    def test_support_tickets_create2(self) -> None:
        """Test case for support_tickets_create2

        """
        pass

    def test_support_tickets_list(self) -> None:
        """Test case for support_tickets_list

        """
        pass

    def test_support_tickets_list2(self) -> None:
        """Test case for support_tickets_list2

        """
        pass

    def test_support_tickets_messages_attachment_retrieve(self) -> None:
        """Test case for support_tickets_messages_attachment_retrieve

        """
        pass

    def test_support_tickets_messages_attachment_retrieve2(self) -> None:
        """Test case for support_tickets_messages_attachment_retrieve2

        """
        pass

    def test_support_tickets_reopen_create(self) -> None:
        """Test case for support_tickets_reopen_create

        """
        pass

    def test_support_tickets_reopen_create2(self) -> None:
        """Test case for support_tickets_reopen_create2

        """
        pass

    def test_support_tickets_reply_create(self) -> None:
        """Test case for support_tickets_reply_create

        """
        pass

    def test_support_tickets_reply_create2(self) -> None:
        """Test case for support_tickets_reply_create2

        """
        pass

    def test_support_tickets_retrieve(self) -> None:
        """Test case for support_tickets_retrieve

        """
        pass

    def test_support_tickets_retrieve2(self) -> None:
        """Test case for support_tickets_retrieve2

        """
        pass


if __name__ == '__main__':
    unittest.main()
