# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.paginated_cluster_detail_list import PaginatedClusterDetailList

class TestPaginatedClusterDetailList(unittest.TestCase):
    """PaginatedClusterDetailList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedClusterDetailList:
        """Test PaginatedClusterDetailList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedClusterDetailList`
        """
        model = PaginatedClusterDetailList()
        if include_optional:
            return PaginatedClusterDetailList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    pidginhost_sdk.models.cluster_detail.ClusterDetail(
                        id = 56, 
                        status = null, 
                        name = '', 
                        cluster_type = '', 
                        kube_version = '', 
                        price_per_month = '-80728880015280.7', 
                        price_per_hour = '', 
                        features = [
                            'cert-manager'
                            ], 
                        features_ready = True, 
                        kubeconfig_valid_until = '', 
                        ipv4_address = '', 
                        protected = True, 
                        talos_version = '', 
                        talos_upgrade_available = '', 
                        talos_next_version = '', 
                        storage_quota_gb = '', 
                        last_pool_used_bytes = '', 
                        last_storage_sync_at = '', )
                    ]
            )
        else:
            return PaginatedClusterDetailList(
                count = 123,
                results = [
                    pidginhost_sdk.models.cluster_detail.ClusterDetail(
                        id = 56, 
                        status = null, 
                        name = '', 
                        cluster_type = '', 
                        kube_version = '', 
                        price_per_month = '-80728880015280.7', 
                        price_per_hour = '', 
                        features = [
                            'cert-manager'
                            ], 
                        features_ready = True, 
                        kubeconfig_valid_until = '', 
                        ipv4_address = '', 
                        protected = True, 
                        talos_version = '', 
                        talos_upgrade_available = '', 
                        talos_next_version = '', 
                        storage_quota_gb = '', 
                        last_pool_used_bytes = '', 
                        last_storage_sync_at = '', )
                    ],
        )
        """

    def testPaginatedClusterDetailList(self):
        """Test PaginatedClusterDetailList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
