# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.api.domain_api import DomainApi


class TestDomainApi(unittest.TestCase):
    """DomainApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainApi()

    def tearDown(self) -> None:
        pass

    def test_domain_domain_cancel_create(self) -> None:
        """Test case for domain_domain_cancel_create

        """
        pass

    def test_domain_domain_check_availability_create(self) -> None:
        """Test case for domain_domain_check_availability_create

        """
        pass

    def test_domain_domain_contacts_create(self) -> None:
        """Test case for domain_domain_contacts_create

        """
        pass

    def test_domain_domain_create(self) -> None:
        """Test case for domain_domain_create

        """
        pass

    def test_domain_domain_list(self) -> None:
        """Test case for domain_domain_list

        """
        pass

    def test_domain_domain_nameservers_create(self) -> None:
        """Test case for domain_domain_nameservers_create

        """
        pass

    def test_domain_domain_partial_update(self) -> None:
        """Test case for domain_domain_partial_update

        """
        pass

    def test_domain_domain_renew_create(self) -> None:
        """Test case for domain_domain_renew_create

        """
        pass

    def test_domain_domain_retrieve(self) -> None:
        """Test case for domain_domain_retrieve

        """
        pass

    def test_domain_domain_transfer_ro_domain_create(self) -> None:
        """Test case for domain_domain_transfer_ro_domain_create

        """
        pass

    def test_domain_domain_update(self) -> None:
        """Test case for domain_domain_update

        """
        pass

    def test_domain_registrants_create(self) -> None:
        """Test case for domain_registrants_create

        """
        pass

    def test_domain_registrants_destroy(self) -> None:
        """Test case for domain_registrants_destroy

        """
        pass

    def test_domain_registrants_list(self) -> None:
        """Test case for domain_registrants_list

        """
        pass

    def test_domain_registrants_partial_update(self) -> None:
        """Test case for domain_registrants_partial_update

        """
        pass

    def test_domain_registrants_retrieve(self) -> None:
        """Test case for domain_registrants_retrieve

        """
        pass

    def test_domain_registrants_update(self) -> None:
        """Test case for domain_registrants_update

        """
        pass

    def test_domain_tld_list(self) -> None:
        """Test case for domain_tld_list

        """
        pass

    def test_domain_tld_retrieve(self) -> None:
        """Test case for domain_tld_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
