# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.lb_upgrade_dispatch_response import LBUpgradeDispatchResponse

class TestLBUpgradeDispatchResponse(unittest.TestCase):
    """LBUpgradeDispatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LBUpgradeDispatchResponse:
        """Test LBUpgradeDispatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LBUpgradeDispatchResponse`
        """
        model = LBUpgradeDispatchResponse()
        if include_optional:
            return LBUpgradeDispatchResponse(
                operation_id = '',
                status = ''
            )
        else:
            return LBUpgradeDispatchResponse(
                operation_id = '',
                status = '',
        )
        """

    def testLBUpgradeDispatchResponse(self):
        """Test LBUpgradeDispatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
