# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.cli_session_poll_response_status_enum import CLISessionPollResponseStatusEnum

class TestCLISessionPollResponseStatusEnum(unittest.TestCase):
    """CLISessionPollResponseStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCLISessionPollResponseStatusEnum(self):
        """Test CLISessionPollResponseStatusEnum"""
        # inst = CLISessionPollResponseStatusEnum()

if __name__ == '__main__':
    unittest.main()
