# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.detach_ipv4_response import DetachIPv4Response

class TestDetachIPv4Response(unittest.TestCase):
    """DetachIPv4Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetachIPv4Response:
        """Test DetachIPv4Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetachIPv4Response`
        """
        model = DetachIPv4Response()
        if include_optional:
            return DetachIPv4Response(
                detached = True
            )
        else:
            return DetachIPv4Response(
                detached = True,
        )
        """

    def testDetachIPv4Response(self):
        """Test DetachIPv4Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
