# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.features_enum import FeaturesEnum

class TestFeaturesEnum(unittest.TestCase):
    """FeaturesEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeaturesEnum(self):
        """Test FeaturesEnum"""
        # inst = FeaturesEnum()

if __name__ == '__main__':
    unittest.main()
