# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.floating_ipv4 import FloatingIPv4

class TestFloatingIPv4(unittest.TestCase):
    """FloatingIPv4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FloatingIPv4:
        """Test FloatingIPv4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FloatingIPv4`
        """
        model = FloatingIPv4()
        if include_optional:
            return FloatingIPv4(
                id = 56,
                address = '',
                gateway = '',
                prefix = 0,
                label = '',
                authorized_vm_count = 56,
                created_at = ''
            )
        else:
            return FloatingIPv4(
                id = 56,
                address = '',
                gateway = '',
                prefix = 0,
                authorized_vm_count = 56,
                created_at = '',
        )
        """

    def testFloatingIPv4(self):
        """Test FloatingIPv4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
