# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.dns_record_create import DNSRecordCreate

class TestDNSRecordCreate(unittest.TestCase):
    """DNSRecordCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DNSRecordCreate:
        """Test DNSRecordCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DNSRecordCreate`
        """
        model = DNSRecordCreate()
        if include_optional:
            return DNSRecordCreate(
                name = '',
                ttl = 56,
                type = 'A',
                address = '',
                cname = '',
                exchange = '',
                preference = 56,
                txtdata = '',
                unencoded = '',
                target = '',
                priority = 56,
                weight = 56,
                port = 56,
                flag = 56,
                tag = '',
                value = '',
                line = 56
            )
        else:
            return DNSRecordCreate(
                name = '',
                ttl = 56,
                type = 'A',
        )
        """

    def testDNSRecordCreate(self):
        """Test DNSRecordCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
