# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.email_service import EmailService

class TestEmailService(unittest.TestCase):
    """EmailService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailService:
        """Test EmailService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailService`
        """
        model = EmailService()
        if include_optional:
            return EmailService(
                id = 56,
                tier = '',
                status = 'pending',
                sandbox_mode = True,
                auto_suspended = True,
                auto_suspend_reason = '',
                msgs_sent_24h = 56,
                msgs_sent_30d = 56,
                bounce_rate_pct = '-807',
                complaint_rate_pct = '-807',
                dedicated_ip_addon = True,
                quota_monthly = '',
                price_monthly_eur = ''
            )
        else:
            return EmailService(
                id = 56,
                tier = '',
                status = 'pending',
                sandbox_mode = True,
                auto_suspended = True,
                auto_suspend_reason = '',
                msgs_sent_24h = 56,
                msgs_sent_30d = 56,
                bounce_rate_pct = '-807',
                complaint_rate_pct = '-807',
                dedicated_ip_addon = True,
                quota_monthly = '',
                price_monthly_eur = '',
        )
        """

    def testEmailService(self):
        """Test EmailService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
