# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.paginated_public_ipv6_list import PaginatedPublicIPv6List

class TestPaginatedPublicIPv6List(unittest.TestCase):
    """PaginatedPublicIPv6List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedPublicIPv6List:
        """Test PaginatedPublicIPv6List
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedPublicIPv6List`
        """
        model = PaginatedPublicIPv6List()
        if include_optional:
            return PaginatedPublicIPv6List(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    pidginhost_sdk.models.public_ipv6.PublicIPv6(
                        id = 56, 
                        slug = '', 
                        address = '', 
                        gateway = '', 
                        prefix = 56, 
                        attached = True, 
                        server = '', )
                    ]
            )
        else:
            return PaginatedPublicIPv6List(
                count = 123,
                results = [
                    pidginhost_sdk.models.public_ipv6.PublicIPv6(
                        id = 56, 
                        slug = '', 
                        address = '', 
                        gateway = '', 
                        prefix = 56, 
                        attached = True, 
                        server = '', )
                    ],
        )
        """

    def testPaginatedPublicIPv6List(self):
        """Test PaginatedPublicIPv6List"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
