# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.api_token_create import APITokenCreate

class TestAPITokenCreate(unittest.TestCase):
    """APITokenCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITokenCreate:
        """Test APITokenCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITokenCreate`
        """
        model = APITokenCreate()
        if include_optional:
            return APITokenCreate(
                id = 56,
                name = '',
                scope = 'read_only',
                key = '',
                created = ''
            )
        else:
            return APITokenCreate(
                id = 56,
                name = '',
                key = '',
                created = '',
        )
        """

    def testAPITokenCreate(self):
        """Test APITokenCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
