# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.server_detach_ipv4_response import ServerDetachIPv4Response

class TestServerDetachIPv4Response(unittest.TestCase):
    """ServerDetachIPv4Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerDetachIPv4Response:
        """Test ServerDetachIPv4Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerDetachIPv4Response`
        """
        model = ServerDetachIPv4Response()
        if include_optional:
            return ServerDetachIPv4Response(
                detached = True
            )
        else:
            return ServerDetachIPv4Response(
                detached = True,
        )
        """

    def testServerDetachIPv4Response(self):
        """Test ServerDetachIPv4Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
