# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.models.paginated_hosting_service_list import PaginatedHostingServiceList

class TestPaginatedHostingServiceList(unittest.TestCase):
    """PaginatedHostingServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHostingServiceList:
        """Test PaginatedHostingServiceList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHostingServiceList`
        """
        model = PaginatedHostingServiceList()
        if include_optional:
            return PaginatedHostingServiceList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    pidginhost_sdk.models.hosting_service.HostingService(
                        id = 56, 
                        hostname = '', 
                        status = null, 
                        price = '-80728880', 
                        next_invoice = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        created = '', 
                        billing_cycle = '', 
                        package_name = '', 
                        node_url = '', 
                        username = '', )
                    ]
            )
        else:
            return PaginatedHostingServiceList(
                count = 123,
                results = [
                    pidginhost_sdk.models.hosting_service.HostingService(
                        id = 56, 
                        hostname = '', 
                        status = null, 
                        price = '-80728880', 
                        next_invoice = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        created = '', 
                        billing_cycle = '', 
                        package_name = '', 
                        node_url = '', 
                        username = '', )
                    ],
        )
        """

    def testPaginatedHostingServiceList(self):
        """Test PaginatedHostingServiceList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
