# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pidginhost_sdk.api.dedicated_api import DedicatedApi


class TestDedicatedApi(unittest.TestCase):
    """DedicatedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DedicatedApi()

    def tearDown(self) -> None:
        pass

    def test_dedicated_servers_list(self) -> None:
        """Test case for dedicated_servers_list

        """
        pass

    def test_dedicated_servers_list2(self) -> None:
        """Test case for dedicated_servers_list2

        """
        pass

    def test_dedicated_servers_power_create(self) -> None:
        """Test case for dedicated_servers_power_create

        """
        pass

    def test_dedicated_servers_power_create2(self) -> None:
        """Test case for dedicated_servers_power_create2

        """
        pass

    def test_dedicated_servers_rdns_create(self) -> None:
        """Test case for dedicated_servers_rdns_create

        """
        pass

    def test_dedicated_servers_rdns_create2(self) -> None:
        """Test case for dedicated_servers_rdns_create2

        """
        pass

    def test_dedicated_servers_reinstall_create(self) -> None:
        """Test case for dedicated_servers_reinstall_create

        """
        pass

    def test_dedicated_servers_reinstall_create2(self) -> None:
        """Test case for dedicated_servers_reinstall_create2

        """
        pass

    def test_dedicated_servers_retrieve(self) -> None:
        """Test case for dedicated_servers_retrieve

        """
        pass

    def test_dedicated_servers_retrieve2(self) -> None:
        """Test case for dedicated_servers_retrieve2

        """
        pass


if __name__ == '__main__':
    unittest.main()
