# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.category_enum import CategoryEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BootISO(BaseModel):
    """
    BootISO
    """ # noqa: E501
    slug: Annotated[str, Field(strict=True, max_length=100)]
    name: Annotated[str, Field(strict=True, max_length=200)]
    description: Optional[Annotated[str, Field(strict=True, max_length=300)]] = None
    category: Optional[CategoryEnum] = None
    min_disk_size: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = Field(default=None, description="GB, 0 = no minimum")
    min_ram: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="GB, 0 = no minimum")
    wipes_disk: Optional[StrictBool] = Field(default=None, description="Installer media — show the data-loss warning")
    compatible: StrictBool
    __properties: ClassVar[List[str]] = ["slug", "name", "description", "category", "min_disk_size", "min_ram", "wipes_disk", "compatible"]

    @field_validator('slug')
    def slug_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[-a-zA-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[-a-zA-Z0-9_]+$/")
        return value

    @field_validator('min_ram')
    def min_ram_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d{0,4}(?:\.\d{0,2})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,4}(?:\.\d{0,2})?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BootISO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "compatible",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BootISO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slug": obj.get("slug"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "category": obj.get("category"),
            "min_disk_size": obj.get("min_disk_size"),
            "min_ram": obj.get("min_ram"),
            "wipes_disk": obj.get("wipes_disk"),
            "compatible": obj.get("compatible")
        })
        return _obj


