# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterEncryptionOperation(BaseModel):
    """
    One encryption change, as the customer sees it.  ``verification_result`` is deliberately absent: the evidence is published once, sanitised, as the state's ``per_node`` -- two copies of a JSON column are two places for key material to escape from.
    """ # noqa: E501
    id: StrictInt
    kind: StrictStr
    status: StrictStr
    requested_mode: StrictStr
    previous_mode: StrictStr
    reason: StrictStr
    message: StrictStr
    override_unverifiable: StrictBool
    request_id: StrictStr
    created_at: StrictStr
    finished_at: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "kind", "status", "requested_mode", "previous_mode", "reason", "message", "override_unverifiable", "request_id", "created_at", "finished_at"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['feature_unavailable', 'cluster_operation_in_progress', 'resource_not_active', 'cluster_not_provisioned', 'invalid_encryption_mode', 'workload_restart_ack_required', 'encryption_state_unknown', 'encryption_already_in_requested_mode', 'reconcile_requires_staff', 'reconcile_requires_unknown_state', 'cilium_version_mismatch', 'kernel_wireguard_unavailable', 'kernel_nodes_unknown', 'helm_upgrade_failed', 'helm_rollback_failed', 'cilium_rollout_failed', 'cilium_node_key_missing', 'cilium_peer_verification_failed', 'cilium_agent_unreadable', 'cilium_agent_state_mismatch', 'cilium_encryption_not_active', 'cilium_encryption_still_active', 'cilium_nodes_unknown', 'cilium_mode_unsupported', 'cilium_verification_misconfigured', 'restart_recheck_failed', 'platform_restart_incomplete', 'encryption_task_aborted', 'dispatch_pending', '']):
            raise ValueError("must be one of enum values ('feature_unavailable', 'cluster_operation_in_progress', 'resource_not_active', 'cluster_not_provisioned', 'invalid_encryption_mode', 'workload_restart_ack_required', 'encryption_state_unknown', 'encryption_already_in_requested_mode', 'reconcile_requires_staff', 'reconcile_requires_unknown_state', 'cilium_version_mismatch', 'kernel_wireguard_unavailable', 'kernel_nodes_unknown', 'helm_upgrade_failed', 'helm_rollback_failed', 'cilium_rollout_failed', 'cilium_node_key_missing', 'cilium_peer_verification_failed', 'cilium_agent_unreadable', 'cilium_agent_state_mismatch', 'cilium_encryption_not_active', 'cilium_encryption_still_active', 'cilium_nodes_unknown', 'cilium_mode_unsupported', 'cilium_verification_misconfigured', 'restart_recheck_failed', 'platform_restart_incomplete', 'encryption_task_aborted', 'dispatch_pending', '')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterEncryptionOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "kind",
            "status",
            "requested_mode",
            "previous_mode",
            "reason",
            "message",
            "override_unverifiable",
            "request_id",
            "created_at",
            "finished_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finished_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterEncryptionOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "status": obj.get("status"),
            "requested_mode": obj.get("requested_mode"),
            "previous_mode": obj.get("previous_mode"),
            "reason": obj.get("reason"),
            "message": obj.get("message"),
            "override_unverifiable": obj.get("override_unverifiable"),
            "request_id": obj.get("request_id"),
            "created_at": obj.get("created_at"),
            "finished_at": obj.get("finished_at")
        })
        return _obj


