# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from pidginhost_sdk.models.encryption_mode_enum import EncryptionModeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterEncryptionReconcileRequest(BaseModel):
    """
    The staff reconcile body, which alone may carry the override.  A SEPARATE component rather than an optional field on the shared one. The toggle route ignores the flag entirely, so declaring it in one body would hand a generated client an argument that silently does nothing on half the routes carrying it -- the same class of published untruth the rest of this feature's schema work exists to prevent.
    """ # noqa: E501
    mode: EncryptionModeEnum = Field(description="Target encryption mode: no encryption, or WireGuard.  * `none` - none * `wireguard` - wireguard")
    acknowledge_workload_restart: Optional[StrictBool] = Field(default=False, description="Confirms the caller accepts that workloads must be restarted after the change.")
    override_unverifiable: Optional[StrictBool] = Field(default=False, description="Record this mode even if verification refuses, together with what was observed. Only the unencrypted mode can be asserted this way: an encrypted state always requires positive per-node evidence.")
    __properties: ClassVar[List[str]] = ["mode", "acknowledge_workload_restart", "override_unverifiable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterEncryptionReconcileRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterEncryptionReconcileRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mode": obj.get("mode"),
            "acknowledge_workload_restart": obj.get("acknowledge_workload_restart") if obj.get("acknowledge_workload_restart") is not None else False,
            "override_unverifiable": obj.get("override_unverifiable") if obj.get("override_unverifiable") is not None else False
        })
        return _obj


