# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.cluster_package import ClusterPackage
from pidginhost_sdk.models.type2fa_enum import Type2faEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterType(BaseModel):
    """
    ClusterType
    """ # noqa: E501
    type: Type2faEnum
    worker_nodes_count_min: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = None
    worker_nodes_count_max: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = None
    worker_node_packages: List[ClusterPackage]
    __properties: ClassVar[List[str]] = ["type", "worker_nodes_count_min", "worker_nodes_count_max", "worker_node_packages"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in worker_node_packages (list)
        _items = []
        if self.worker_node_packages:
            for _item_worker_node_packages in self.worker_node_packages:
                if _item_worker_node_packages:
                    _items.append(_item_worker_node_packages.to_dict())
            _dict['worker_node_packages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "worker_nodes_count_min": obj.get("worker_nodes_count_min"),
            "worker_nodes_count_max": obj.get("worker_nodes_count_max"),
            "worker_node_packages": [ClusterPackage.from_dict(_item) for _item in obj["worker_node_packages"]] if obj.get("worker_node_packages") is not None else None
        })
        return _obj


