# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FeaturesEnum(str, Enum):
    """
    * `cert-manager` - Certificate manager * `ceph-csi` - Ceph CSI * `metrics-server` - Metrics Server * `cloudnative-pg` - CloudNative PG * `mariadb-operator` - MariaDB Operator
    """

    """
    allowed enum values
    """
    CERT_MINUS_MANAGER = 'cert-manager'
    CEPH_MINUS_CSI = 'ceph-csi'
    METRICS_MINUS_SERVER = 'metrics-server'
    CLOUDNATIVE_MINUS_PG = 'cloudnative-pg'
    MARIADB_MINUS_OPERATOR = 'mariadb-operator'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FeaturesEnum from a JSON string"""
        return cls(json.loads(json_str))


