# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.firewall_rule_direction_enum import FirewallRuleDirectionEnum
from pidginhost_sdk.models.fw_policy_out_enum import FwPolicyOutEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FirewallRule(BaseModel):
    """
    FirewallRule
    """ # noqa: E501
    id: StrictInt
    direction: FirewallRuleDirectionEnum
    action: FwPolicyOutEnum
    protocol: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    source: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="single IP, range (20.34.101.207-201.3.9.99) or comma separated list")
    sport: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="numbers (0-65535), range (\"\\d+:\\d+\", like \"80:85\"), comma separated list")
    destination: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="single IP, range (20.34.101.207-201.3.9.99) or comma separated list")
    dport: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="numbers (0-65535), range (\"\\d+:\\d+\", like \"80:85\"), comma separated list")
    enabled: Optional[StrictBool] = None
    position: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = None
    has_error: StrictBool
    error_message: StrictStr
    __properties: ClassVar[List[str]] = ["id", "direction", "action", "protocol", "source", "sport", "destination", "dport", "enabled", "position", "has_error", "error_message"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FirewallRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "has_error",
            "error_message",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FirewallRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "direction": obj.get("direction"),
            "action": obj.get("action"),
            "protocol": obj.get("protocol"),
            "source": obj.get("source"),
            "sport": obj.get("sport"),
            "destination": obj.get("destination"),
            "dport": obj.get("dport"),
            "enabled": obj.get("enabled"),
            "position": obj.get("position"),
            "has_error": obj.get("has_error"),
            "error_message": obj.get("error_message")
        })
        return _obj


