# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class KubeVersionEnum(str, Enum):
    """
    * `1.33.13` - 1.33.13 * `1.34.10` - 1.34.10 * `1.35.7` - 1.35.7 * `1.36.3` - 1.36.3
    """

    """
    allowed enum values
    """
    ENUM_1_DOT_33_DOT_13 = '1.33.13'
    ENUM_1_DOT_34_DOT_10 = '1.34.10'
    ENUM_1_DOT_35_DOT_7 = '1.35.7'
    ENUM_1_DOT_36_DOT_3 = '1.36.3'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KubeVersionEnum from a JSON string"""
        return cls(json.loads(json_str))


