# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.address import Address
from typing import Optional, Set
from typing_extensions import Self

class PatchedCompany(BaseModel):
    """
    PatchedCompany
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    cif_vat: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    reg: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    iban: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    bank: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    contact_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    contact_email: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    address: Optional[Address] = None
    __properties: ClassVar[List[str]] = ["id", "name", "cif_vat", "reg", "iban", "bank", "contact_name", "contact_email", "address"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedCompany from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedCompany from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "cif_vat": obj.get("cif_vat"),
            "reg": obj.get("reg"),
            "iban": obj.get("iban"),
            "bank": obj.get("bank"),
            "contact_name": obj.get("contact_name"),
            "contact_email": obj.get("contact_email"),
            "address": Address.from_dict(obj["address"]) if obj.get("address") is not None else None
        })
        return _obj


