# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.service import Service
from pidginhost_sdk.models.tld import TLD
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchedDomain(BaseModel):
    """
    PatchedDomain
    """ # noqa: E501
    id: Optional[StrictInt] = None
    domain: Optional[StrictStr] = None
    tld: Optional[TLD] = None
    idna: Optional[StrictBool] = Field(default=None, description="Domain name is encoded with IDN")
    nameservers: Optional[Annotated[str, Field(strict=True, max_length=1200)]] = Field(default=None, description="List of 2-5 name-servers separated by comma.")
    expiration_date: Optional[date] = None
    registration_date: Optional[date] = None
    service: Optional[Service] = None
    idna_name: Optional[StrictStr] = None
    max_renew_years: Optional[StrictInt] = None
    service_status: Optional[StrictStr] = Field(default=None, description="Service status")
    contacts: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["id", "domain", "tld", "idna", "nameservers", "expiration_date", "registration_date", "service", "idna_name", "max_renew_years", "service_status", "contacts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedDomain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "domain",
            "tld",
            "idna",
            "expiration_date",
            "registration_date",
            "service",
            "idna_name",
            "max_renew_years",
            "service_status",
            "contacts",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tld
        if self.tld:
            _dict['tld'] = self.tld.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        # set to None if registration_date (nullable) is None
        # and model_fields_set contains the field
        if self.registration_date is None and "registration_date" in self.model_fields_set:
            _dict['registration_date'] = None

        # set to None if contacts (nullable) is None
        # and model_fields_set contains the field
        if self.contacts is None and "contacts" in self.model_fields_set:
            _dict['contacts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedDomain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "domain": obj.get("domain"),
            "tld": TLD.from_dict(obj["tld"]) if obj.get("tld") is not None else None,
            "idna": obj.get("idna"),
            "nameservers": obj.get("nameservers"),
            "expiration_date": obj.get("expiration_date"),
            "registration_date": obj.get("registration_date"),
            "service": Service.from_dict(obj["service"]) if obj.get("service") is not None else None,
            "idna_name": obj.get("idna_name"),
            "max_renew_years": obj.get("max_renew_years"),
            "service_status": obj.get("service_status"),
            "contacts": obj.get("contacts")
        })
        return _obj


