# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.country_enum import CountryEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchedDomainRegistrant(BaseModel):
    """
    PatchedDomainRegistrant
    """ # noqa: E501
    id: Optional[StrictInt] = None
    first_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    last_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    company: Optional[Annotated[str, Field(strict=True, max_length=40)]] = None
    address: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    city: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    region: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    postal_code: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    country: Optional[CountryEnum] = None
    email: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    phone: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    cif_cnp: Optional[Annotated[str, Field(strict=True, max_length=40)]] = None
    reg_com: Optional[Annotated[str, Field(strict=True, max_length=40)]] = None
    __properties: ClassVar[List[str]] = ["id", "first_name", "last_name", "company", "address", "city", "region", "postal_code", "country", "email", "phone", "cif_cnp", "reg_com"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedDomainRegistrant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if company (nullable) is None
        # and model_fields_set contains the field
        if self.company is None and "company" in self.model_fields_set:
            _dict['company'] = None

        # set to None if cif_cnp (nullable) is None
        # and model_fields_set contains the field
        if self.cif_cnp is None and "cif_cnp" in self.model_fields_set:
            _dict['cif_cnp'] = None

        # set to None if reg_com (nullable) is None
        # and model_fields_set contains the field
        if self.reg_com is None and "reg_com" in self.model_fields_set:
            _dict['reg_com'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedDomainRegistrant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "company": obj.get("company"),
            "address": obj.get("address"),
            "city": obj.get("city"),
            "region": obj.get("region"),
            "postal_code": obj.get("postal_code"),
            "country": obj.get("country"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "cif_cnp": obj.get("cif_cnp"),
            "reg_com": obj.get("reg_com")
        })
        return _obj


