# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.status_a57_enum import StatusA57Enum
from pidginhost_sdk.models.volume import Volume
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchedServerDetail(BaseModel):
    """
    PatchedServerDetail
    """ # noqa: E501
    id: Optional[StrictInt] = None
    hostname: Optional[StrictStr] = None
    project: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    image: Optional[StrictStr] = None
    package: Optional[StrictStr] = None
    cpus: Optional[StrictInt] = None
    memory: Optional[StrictInt] = None
    disk_size: Optional[StrictInt] = None
    generation: Optional[StrictStr] = None
    machine: Optional[Dict[str, Any]] = None
    volumes: Optional[List[Volume]] = None
    networks: Optional[Dict[str, Any]] = None
    password: Optional[Annotated[str, Field(strict=True, max_length=300)]] = None
    status: Optional[StatusA57Enum] = None
    username: Optional[StrictStr] = None
    destroy_protection: Optional[StrictBool] = Field(default=None, description="Prevents the server from being destroyed until disabled.")
    ha_enabled: Optional[StrictBool] = Field(default=None, description="Enables Proxmox HA — automatic restart and migration on node failure.")
    __properties: ClassVar[List[str]] = ["id", "hostname", "project", "image", "package", "cpus", "memory", "disk_size", "generation", "machine", "volumes", "networks", "password", "status", "username", "destroy_protection", "ha_enabled"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedServerDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "hostname",
            "image",
            "package",
            "cpus",
            "memory",
            "disk_size",
            "generation",
            "machine",
            "volumes",
            "networks",
            "status",
            "username",
            "destroy_protection",
            "ha_enabled",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict['volumes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedServerDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "hostname": obj.get("hostname"),
            "project": obj.get("project"),
            "image": obj.get("image"),
            "package": obj.get("package"),
            "cpus": obj.get("cpus"),
            "memory": obj.get("memory"),
            "disk_size": obj.get("disk_size"),
            "generation": obj.get("generation"),
            "machine": obj.get("machine"),
            "volumes": [Volume.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None,
            "networks": obj.get("networks"),
            "password": obj.get("password"),
            "status": obj.get("status"),
            "username": obj.get("username"),
            "destroy_protection": obj.get("destroy_protection"),
            "ha_enabled": obj.get("ha_enabled")
        })
        return _obj


