# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PoolRemovalItem(BaseModel):
    """
    One worker a journal is removing, and how far its removal got.
    """ # noqa: E501
    target_hostname: StrictStr
    cordoned_at: Optional[StrictStr]
    drained_at: Optional[StrictStr]
    detached_at: Optional[StrictStr]
    validated_at: Optional[StrictStr]
    reset_started_at: Optional[StrictStr]
    reset_completed_at: Optional[StrictStr]
    node_deleted_at: Optional[StrictStr]
    vm_deleted_at: Optional[StrictStr]
    uncordoned_at: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["target_hostname", "cordoned_at", "drained_at", "detached_at", "validated_at", "reset_started_at", "reset_completed_at", "node_deleted_at", "vm_deleted_at", "uncordoned_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PoolRemovalItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "target_hostname",
            "cordoned_at",
            "drained_at",
            "detached_at",
            "validated_at",
            "reset_started_at",
            "reset_completed_at",
            "node_deleted_at",
            "vm_deleted_at",
            "uncordoned_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cordoned_at (nullable) is None
        # and model_fields_set contains the field
        if self.cordoned_at is None and "cordoned_at" in self.model_fields_set:
            _dict['cordoned_at'] = None

        # set to None if drained_at (nullable) is None
        # and model_fields_set contains the field
        if self.drained_at is None and "drained_at" in self.model_fields_set:
            _dict['drained_at'] = None

        # set to None if detached_at (nullable) is None
        # and model_fields_set contains the field
        if self.detached_at is None and "detached_at" in self.model_fields_set:
            _dict['detached_at'] = None

        # set to None if validated_at (nullable) is None
        # and model_fields_set contains the field
        if self.validated_at is None and "validated_at" in self.model_fields_set:
            _dict['validated_at'] = None

        # set to None if reset_started_at (nullable) is None
        # and model_fields_set contains the field
        if self.reset_started_at is None and "reset_started_at" in self.model_fields_set:
            _dict['reset_started_at'] = None

        # set to None if reset_completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.reset_completed_at is None and "reset_completed_at" in self.model_fields_set:
            _dict['reset_completed_at'] = None

        # set to None if node_deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.node_deleted_at is None and "node_deleted_at" in self.model_fields_set:
            _dict['node_deleted_at'] = None

        # set to None if vm_deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.vm_deleted_at is None and "vm_deleted_at" in self.model_fields_set:
            _dict['vm_deleted_at'] = None

        # set to None if uncordoned_at (nullable) is None
        # and model_fields_set contains the field
        if self.uncordoned_at is None and "uncordoned_at" in self.model_fields_set:
            _dict['uncordoned_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PoolRemovalItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "target_hostname": obj.get("target_hostname"),
            "cordoned_at": obj.get("cordoned_at"),
            "drained_at": obj.get("drained_at"),
            "detached_at": obj.get("detached_at"),
            "validated_at": obj.get("validated_at"),
            "reset_started_at": obj.get("reset_started_at"),
            "reset_completed_at": obj.get("reset_completed_at"),
            "node_deleted_at": obj.get("node_deleted_at"),
            "vm_deleted_at": obj.get("vm_deleted_at"),
            "uncordoned_at": obj.get("uncordoned_at")
        })
        return _obj


