# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pidginhost_sdk.models.fw_policy_out_enum import FwPolicyOutEnum
from typing import Optional, Set
from typing_extensions import Self

class PublicInterface(BaseModel):
    """
    PublicInterface
    """ # noqa: E501
    interface: StrictStr
    ipv4: StrictStr
    ipv6: StrictStr
    fw_rules_set: Optional[StrictStr] = Field(default=None, description="ID or slug")
    fw_policy_in: Optional[FwPolicyOutEnum] = None
    fw_policy_out: Optional[FwPolicyOutEnum] = None
    __properties: ClassVar[List[str]] = ["interface", "ipv4", "ipv6", "fw_rules_set", "fw_policy_in", "fw_policy_out"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicInterface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "interface",
            "ipv4",
            "ipv6",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fw_rules_set (nullable) is None
        # and model_fields_set contains the field
        if self.fw_rules_set is None and "fw_rules_set" in self.model_fields_set:
            _dict['fw_rules_set'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicInterface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "interface": obj.get("interface"),
            "ipv4": obj.get("ipv4"),
            "ipv6": obj.get("ipv6"),
            "fw_rules_set": obj.get("fw_rules_set"),
            "fw_policy_in": obj.get("fw_policy_in"),
            "fw_policy_out": obj.get("fw_policy_out")
        })
        return _obj


