# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pidginhost_sdk.models.dns_source_enum import DnsSourceEnum
from pidginhost_sdk.models.sending_domain_status_enum import SendingDomainStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendingDomain(BaseModel):
    """
    SendingDomain
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    status: SendingDomainStatusEnum
    dns_source: DnsSourceEnum
    use_inbound: StrictBool
    dkim_selector: StrictStr
    dkim_record: StrictStr
    spf_record: StrictStr
    dmarc_record: StrictStr
    verified_at: Optional[StrictStr]
    last_check_at: Optional[StrictStr]
    last_check_errors: Optional[Any]
    __properties: ClassVar[List[str]] = ["id", "name", "status", "dns_source", "use_inbound", "dkim_selector", "dkim_record", "spf_record", "dmarc_record", "verified_at", "last_check_at", "last_check_errors"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendingDomain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "name",
            "status",
            "dns_source",
            "use_inbound",
            "dkim_selector",
            "dkim_record",
            "spf_record",
            "dmarc_record",
            "verified_at",
            "last_check_at",
            "last_check_errors",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if verified_at (nullable) is None
        # and model_fields_set contains the field
        if self.verified_at is None and "verified_at" in self.model_fields_set:
            _dict['verified_at'] = None

        # set to None if last_check_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_check_at is None and "last_check_at" in self.model_fields_set:
            _dict['last_check_at'] = None

        # set to None if last_check_errors (nullable) is None
        # and model_fields_set contains the field
        if self.last_check_errors is None and "last_check_errors" in self.model_fields_set:
            _dict['last_check_errors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendingDomain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "dns_source": obj.get("dns_source"),
            "use_inbound": obj.get("use_inbound"),
            "dkim_selector": obj.get("dkim_selector"),
            "dkim_record": obj.get("dkim_record"),
            "spf_record": obj.get("spf_record"),
            "dmarc_record": obj.get("dmarc_record"),
            "verified_at": obj.get("verified_at"),
            "last_check_at": obj.get("last_check_at"),
            "last_check_errors": obj.get("last_check_errors")
        })
        return _obj


