# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ServerTrafficResponse(BaseModel):
    """
    ServerTrafficResponse
    """ # noqa: E501
    year: StrictInt
    month: StrictInt
    as_of: Optional[date]
    status: StrictStr
    bytes_in: StrictInt
    bytes_out: StrictInt
    bytes_total: StrictInt
    included_tb: Optional[StrictInt]
    used_units: StrictInt
    used_tb: StrictStr = Field(description="Usage rounded up to six decimal places; bytes_total is exact.")
    billable_bytes: StrictInt = Field(description="Of bytes_total, the part that may be charged.")
    billable_units: StrictInt
    billable_tb: StrictStr = Field(description="Billable usage rounded up to six decimal places; billable_bytes is exact.")
    billable_from: Optional[date] = Field(description="First fully billable day, when one date describes the usage. May fall after the reported month. Null when all usage is billable or streams have different boundaries; use billable_bytes for the billable total.")
    charged_tb: StrictInt
    charged_amount: StrictStr
    price_per_tb: Optional[StrictStr]
    currency: StrictStr
    unit_bytes: StrictInt
    remaining_bytes: Optional[StrictInt]
    last_sample_at: Optional[date]
    daily: List[Dict[str, Any]]
    __properties: ClassVar[List[str]] = ["year", "month", "as_of", "status", "bytes_in", "bytes_out", "bytes_total", "included_tb", "used_units", "used_tb", "billable_bytes", "billable_units", "billable_tb", "billable_from", "charged_tb", "charged_amount", "price_per_tb", "currency", "unit_bytes", "remaining_bytes", "last_sample_at", "daily"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerTrafficResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if as_of (nullable) is None
        # and model_fields_set contains the field
        if self.as_of is None and "as_of" in self.model_fields_set:
            _dict['as_of'] = None

        # set to None if included_tb (nullable) is None
        # and model_fields_set contains the field
        if self.included_tb is None and "included_tb" in self.model_fields_set:
            _dict['included_tb'] = None

        # set to None if billable_from (nullable) is None
        # and model_fields_set contains the field
        if self.billable_from is None and "billable_from" in self.model_fields_set:
            _dict['billable_from'] = None

        # set to None if price_per_tb (nullable) is None
        # and model_fields_set contains the field
        if self.price_per_tb is None and "price_per_tb" in self.model_fields_set:
            _dict['price_per_tb'] = None

        # set to None if remaining_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.remaining_bytes is None and "remaining_bytes" in self.model_fields_set:
            _dict['remaining_bytes'] = None

        # set to None if last_sample_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_sample_at is None and "last_sample_at" in self.model_fields_set:
            _dict['last_sample_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerTrafficResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "year": obj.get("year"),
            "month": obj.get("month"),
            "as_of": obj.get("as_of"),
            "status": obj.get("status"),
            "bytes_in": obj.get("bytes_in"),
            "bytes_out": obj.get("bytes_out"),
            "bytes_total": obj.get("bytes_total"),
            "included_tb": obj.get("included_tb"),
            "used_units": obj.get("used_units"),
            "used_tb": obj.get("used_tb"),
            "billable_bytes": obj.get("billable_bytes"),
            "billable_units": obj.get("billable_units"),
            "billable_tb": obj.get("billable_tb"),
            "billable_from": obj.get("billable_from"),
            "charged_tb": obj.get("charged_tb"),
            "charged_amount": obj.get("charged_amount"),
            "price_per_tb": obj.get("price_per_tb"),
            "currency": obj.get("currency"),
            "unit_bytes": obj.get("unit_bytes"),
            "remaining_bytes": obj.get("remaining_bytes"),
            "last_sample_at": obj.get("last_sample_at"),
            "daily": obj.get("daily")
        })
        return _obj


