# coding: utf-8

"""
    Pidgin Host API

    The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

    The version of the OpenAPI document: 1.0.0 (v1)
    Contact: support@pidginhost.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pidginhost_sdk.models.floating_ip_summary import FloatingIPSummary
from pidginhost_sdk.models.resource_status_enum import ResourceStatusEnum
from pidginhost_sdk.models.volume import Volume
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ServerDetail(BaseModel):
    """
    ServerDetail
    """ # noqa: E501
    id: StrictInt
    hostname: StrictStr
    project: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    image: StrictStr
    package: StrictStr
    cpus: StrictInt
    memory: StrictInt
    disk_size: StrictInt
    generation: StrictStr
    machine: Dict[str, Any]
    volumes: List[Volume]
    networks: Dict[str, Any]
    floating_ips: List[FloatingIPSummary]
    password: Optional[Annotated[str, Field(strict=True, max_length=300)]] = None
    ssh_pub_key: Optional[Annotated[str, Field(strict=True, max_length=3000)]] = Field(default=None, description="Public key to apply for SSH login. Applying a non-empty key regenerates cloud-init and reboots a running server. Clearing removes the key from future cloud-init data, but does not revoke keys already in the guest.")
    status: ResourceStatusEnum
    username: StrictStr
    destroy_protection: StrictBool = Field(description="Prevents the server from being destroyed until disabled.")
    ha_enabled: StrictBool = Field(description="Enables Proxmox HA — automatic restart and migration on node failure.")
    custom_os: StrictBool = Field(description="Customer installed their own OS from an ISO; cloud-init features no longer apply")
    rescue_mode: StrictBool
    boot_iso: Optional[StrictStr]
    rescue_supported: StrictBool
    __properties: ClassVar[List[str]] = ["id", "hostname", "project", "image", "package", "cpus", "memory", "disk_size", "generation", "machine", "volumes", "networks", "floating_ips", "password", "ssh_pub_key", "status", "username", "destroy_protection", "ha_enabled", "custom_os", "rescue_mode", "boot_iso", "rescue_supported"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "hostname",
            "image",
            "package",
            "cpus",
            "memory",
            "disk_size",
            "generation",
            "machine",
            "volumes",
            "networks",
            "floating_ips",
            "status",
            "username",
            "destroy_protection",
            "ha_enabled",
            "custom_os",
            "rescue_mode",
            "boot_iso",
            "rescue_supported",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict['volumes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in floating_ips (list)
        _items = []
        if self.floating_ips:
            for _item_floating_ips in self.floating_ips:
                if _item_floating_ips:
                    _items.append(_item_floating_ips.to_dict())
            _dict['floating_ips'] = _items
        # set to None if boot_iso (nullable) is None
        # and model_fields_set contains the field
        if self.boot_iso is None and "boot_iso" in self.model_fields_set:
            _dict['boot_iso'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "hostname": obj.get("hostname"),
            "project": obj.get("project"),
            "image": obj.get("image"),
            "package": obj.get("package"),
            "cpus": obj.get("cpus"),
            "memory": obj.get("memory"),
            "disk_size": obj.get("disk_size"),
            "generation": obj.get("generation"),
            "machine": obj.get("machine"),
            "volumes": [Volume.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None,
            "networks": obj.get("networks"),
            "floating_ips": [FloatingIPSummary.from_dict(_item) for _item in obj["floating_ips"]] if obj.get("floating_ips") is not None else None,
            "password": obj.get("password"),
            "ssh_pub_key": obj.get("ssh_pub_key"),
            "status": obj.get("status"),
            "username": obj.get("username"),
            "destroy_protection": obj.get("destroy_protection"),
            "ha_enabled": obj.get("ha_enabled"),
            "custom_os": obj.get("custom_os"),
            "rescue_mode": obj.get("rescue_mode"),
            "boot_iso": obj.get("boot_iso"),
            "rescue_supported": obj.get("rescue_supported")
        })
        return _obj


